### ISSUE TITLE
fping6 no more builds: incompatible types when assigning to type ‘struct in_addr’ from type ‘struct in6_addr’

### ISSUE THREAD

**Issue by xtaran** [schweikert/fping#54]
Hi David,

while fping 3.6 builds fine on Debian Unstable, fping 3.7 fails to build:

```
Making all in src
make[4]: Entering directory `/home/abe/fping/fping/build/ipv6/src'
gcc -DHAVE_CONFIG_H -I. -I../../src -I..   -DIPV6=1 -D_FORTIFY_SOURCE=2  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -MT fping.o -MD -MP -MF .deps/fping.Tpo -c -o fping.o ../../src/fping.c
../../src/fping.c: In function ‘main’:
../../src/fping.c:371:16: warning: ignoring return value of ‘seteuid’, declared with attribute warn_unused_result [-Wunused-result]
         seteuid( getuid() );
                ^
mv -f .deps/fping.Tpo .deps/fping.Po
gcc -DHAVE_CONFIG_H -I. -I../../src -I..   -DIPV6=1 -D_FORTIFY_SOURCE=2  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -MT seqmap.o -MD -MP -MF .deps/seqmap.Tpo -c -o seqmap.o ../../src/seqmap.c
mv -f .deps/seqmap.Tpo .deps/seqmap.Po
gcc -DHAVE_CONFIG_H -I. -I../../src -I..   -DIPV6=1 -D_FORTIFY_SOURCE=2  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -MT socket.o -MD -MP -MF .deps/socket.Tpo -c -o socket.o ../../src/socket.c
mv -f .deps/socket.Tpo .deps/socket.Po
gcc -DHAVE_CONFIG_H -I. -I../../src -I..   -DIPV6=1 -D_FORTIFY_SOURCE=2  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -MT socket4.o -MD -MP -MF .deps/socket4.Tpo -c -o socket4.o ../../src/socket4.c
../../src/socket4.c: In function ‘socket_set_src_addr_ipv4’:
../../src/socket4.c:69:17: error: incompatible types when assigning to type ‘struct in_addr’ from type ‘struct in6_addr’
     sa.sin_addr = src_addr;
                 ^
make[4]: *** [socket4.o] Error 1
make[4]: Leaving directory `/home/abe/fping/fping/build/ipv6/src'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/abe/fping/fping/build/ipv6'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/abe/fping/fping/build/ipv6'
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory `/home/abe/fping/fping'
make: *** [build] Error 2
```
